-- ============================================================
-- ClickTake Technologies — Supabase Setup Script
-- Paste this entire file into: Supabase Dashboard → SQL Editor
--   → New Query → paste → Run
-- Creates all 28 tables + seeds all data (idempotent).
-- ============================================================

-- Enable statement timeout extension for long-running seed
SET statement_timeout = '120s';

-- ============================================
-- 1. CREATE ALL TABLES (28 tables)
-- ============================================
CREATE TABLE IF NOT EXISTS "User" (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT, password TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'admin', permissions TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "Page" (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'custom', status TEXT NOT NULL DEFAULT 'published', hero TEXT, overview TEXT, body TEXT, "metaTitle" TEXT, "metaDescription" TEXT, keywords TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "BlogPost" (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'General', excerpt TEXT NOT NULL, body TEXT, status TEXT NOT NULL DEFAULT 'published', "readTime" TEXT NOT NULL DEFAULT '5 min', "metaTitle" TEXT, "metaDescription" TEXT, keywords TEXT, "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "PricingTier" (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, tagline TEXT NOT NULL, audience TEXT NOT NULL, price TEXT NOT NULL, cadence TEXT NOT NULL, popular BOOLEAN NOT NULL DEFAULT false, features TEXT NOT NULL, "notIncluded" TEXT, cta TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'published', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "ContactQuery" (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, company TEXT, need TEXT, message TEXT, source TEXT NOT NULL DEFAULT 'contact', status TEXT NOT NULL DEFAULT 'new', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "JobApplication" (id TEXT PRIMARY KEY, "jobId" TEXT NOT NULL, "positionType" TEXT, "fullName" TEXT NOT NULL, email TEXT NOT NULL, mobile TEXT, "filesFolder" TEXT, "filesManifest" TEXT, status TEXT NOT NULL DEFAULT 'new', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "SeoAudit" (id TEXT PRIMARY KEY, url TEXT NOT NULL, score INTEGER NOT NULL DEFAULT 0, "titleLen" INTEGER NOT NULL DEFAULT 0, "descLen" INTEGER NOT NULL DEFAULT 0, "h1Count" INTEGER NOT NULL DEFAULT 0, "hasCanonical" BOOLEAN NOT NULL DEFAULT false, "hasOg" BOOLEAN NOT NULL DEFAULT false, "hasJsonLd" BOOLEAN NOT NULL DEFAULT false, "hasSitemap" BOOLEAN NOT NULL DEFAULT false, "hasRobots" BOOLEAN NOT NULL DEFAULT false, issues TEXT, notes TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "MediaAsset" (id TEXT PRIMARY KEY, name TEXT NOT NULL, url TEXT NOT NULL, mime TEXT NOT NULL, size INTEGER NOT NULL DEFAULT 0, alt TEXT, folder TEXT NOT NULL DEFAULT 'uploads', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "Redirect" (id TEXT PRIMARY KEY, "from" TEXT NOT NULL UNIQUE, "to" TEXT NOT NULL, status INTEGER NOT NULL DEFAULT 301, active BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "SiteSetting" (id TEXT PRIMARY KEY, key TEXT NOT NULL UNIQUE, value TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'general', "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "ActivityLog" (id TEXT PRIMARY KEY, action TEXT NOT NULL, entity TEXT NOT NULL, "entityId" TEXT, summary TEXT NOT NULL, actor TEXT NOT NULL DEFAULT 'admin', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "Lead" (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, company TEXT, source TEXT NOT NULL DEFAULT 'website', stage TEXT NOT NULL DEFAULT 'new', value TEXT, notes TEXT, tags TEXT, owner TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "EmailTemplate" (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, subject TEXT NOT NULL, body TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'transactional', status TEXT NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "Experiment" (id TEXT PRIMARY KEY, name TEXT NOT NULL, hypothesis TEXT NOT NULL, page TEXT NOT NULL, "variantA" TEXT NOT NULL, "variantB" TEXT NOT NULL, metric TEXT NOT NULL DEFAULT 'conversion', status TEXT NOT NULL DEFAULT 'draft', "visitorsA" INTEGER NOT NULL DEFAULT 0, "visitorsB" INTEGER NOT NULL DEFAULT 0, "convA" INTEGER NOT NULL DEFAULT 0, "convB" INTEGER NOT NULL DEFAULT 0, winner TEXT, "startDate" TIMESTAMP(3), "endDate" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "ThemeVariable" (id TEXT PRIMARY KEY, key TEXT NOT NULL UNIQUE, value TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'color', "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "TypographyPreset" (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, "fontFamily" TEXT NOT NULL, "headingScale" TEXT NOT NULL, "bodySize" TEXT NOT NULL, "lineHeight" TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SecurityLog" (id TEXT PRIMARY KEY, type TEXT NOT NULL, ip TEXT, email TEXT, detail TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SiteVisit" (id TEXT PRIMARY KEY, path TEXT NOT NULL, referrer TEXT, country TEXT, device TEXT NOT NULL DEFAULT 'desktop', browser TEXT, "sessionId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "TeamMember" (id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL, department TEXT NOT NULL, bio TEXT, photo TEXT, linkedin TEXT, twitter TEXT, "order" INTEGER NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "Job" (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, department TEXT NOT NULL, location TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'Full-time', description TEXT NOT NULL, requirements TEXT, salary TEXT, active BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "Keyword" (id TEXT PRIMARY KEY, keyword TEXT NOT NULL UNIQUE, type TEXT NOT NULL DEFAULT 'commercial', volume INTEGER NOT NULL DEFAULT 0, difficulty INTEGER NOT NULL DEFAULT 0, cpc TEXT, intent TEXT, status TEXT NOT NULL DEFAULT 'tracking', "currentRank" INTEGER, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "Ranking" (id TEXT PRIMARY KEY, keyword TEXT NOT NULL, position INTEGER NOT NULL, engine TEXT NOT NULL DEFAULT 'google', "serpFeature" TEXT, url TEXT, date TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "AiMention" (id TEXT PRIMARY KEY, prompt TEXT NOT NULL, platform TEXT NOT NULL, mentioned BOOLEAN NOT NULL DEFAULT false, sentiment TEXT, citation TEXT, response TEXT, date TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "Backlink" (id TEXT PRIMARY KEY, "sourceUrl" TEXT NOT NULL, "targetUrl" TEXT NOT NULL, "anchorText" TEXT, "domainRating" INTEGER NOT NULL DEFAULT 0, dofollow BOOLEAN NOT NULL DEFAULT true, status TEXT NOT NULL DEFAULT 'active', "firstSeen" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastSeen" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "ContentBrief" (id TEXT PRIMARY KEY, title TEXT NOT NULL, keyword TEXT NOT NULL, headings TEXT, faqs TEXT, entities TEXT, "wordCount" INTEGER NOT NULL DEFAULT 0, "seoScore" INTEGER NOT NULL DEFAULT 0, "aeoScore" INTEGER NOT NULL DEFAULT 0, "geoScore" INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "SeoIssue" (id TEXT PRIMARY KEY, type TEXT NOT NULL, severity TEXT NOT NULL DEFAULT 'warning', url TEXT NOT NULL, detail TEXT NOT NULL, "fixSuggestion" TEXT, status TEXT NOT NULL DEFAULT 'open', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "SeoReport" (id TEXT PRIMARY KEY, type TEXT NOT NULL, score INTEGER NOT NULL DEFAULT 0, summary TEXT, data TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "ClientLogo" (id TEXT PRIMARY KEY, name TEXT NOT NULL, logo TEXT NOT NULL, website TEXT, category TEXT NOT NULL DEFAULT 'general', "order" INTEGER NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "Post" (id TEXT PRIMARY KEY, title TEXT NOT NULL, content TEXT, published BOOLEAN NOT NULL DEFAULT false, "authorId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);

-- ============================================
-- 2. CREATE INDEXES
-- ============================================
CREATE INDEX IF NOT EXISTS Page_status_idx ON "Page" ("status");
CREATE INDEX IF NOT EXISTS Page_category_idx ON "Page" ("category");
CREATE INDEX IF NOT EXISTS BlogPost_status_idx ON "BlogPost" ("status");
CREATE INDEX IF NOT EXISTS BlogPost_category_idx ON "BlogPost" ("category");
CREATE INDEX IF NOT EXISTS ContactQuery_status_idx ON "ContactQuery" ("status");
CREATE INDEX IF NOT EXISTS ContactQuery_source_idx ON "ContactQuery" ("source");
CREATE INDEX IF NOT EXISTS JobApplication_status_idx ON "JobApplication" ("status");
CREATE INDEX IF NOT EXISTS JobApplication_jobId_idx ON "JobApplication" ("jobId");
CREATE INDEX IF NOT EXISTS MediaAsset_folder_idx ON "MediaAsset" ("folder");
CREATE INDEX IF NOT EXISTS MediaAsset_mime_idx ON "MediaAsset" ("mime");
CREATE INDEX IF NOT EXISTS ActivityLog_entity_idx ON "ActivityLog" ("entity");
CREATE INDEX IF NOT EXISTS ActivityLog_action_idx ON "ActivityLog" ("action");
CREATE INDEX IF NOT EXISTS ActivityLog_createdAt_idx ON "ActivityLog" ("createdAt");
CREATE INDEX IF NOT EXISTS Lead_stage_idx ON "Lead" ("stage");
CREATE INDEX IF NOT EXISTS Lead_source_idx ON "Lead" ("source");
CREATE INDEX IF NOT EXISTS Lead_owner_idx ON "Lead" ("owner");
CREATE INDEX IF NOT EXISTS EmailTemplate_category_idx ON "EmailTemplate" ("category");
CREATE INDEX IF NOT EXISTS EmailTemplate_status_idx ON "EmailTemplate" ("status");
CREATE INDEX IF NOT EXISTS Experiment_status_idx ON "Experiment" ("status");
CREATE INDEX IF NOT EXISTS SecurityLog_type_idx ON "SecurityLog" ("type");
CREATE INDEX IF NOT EXISTS SecurityLog_createdAt_idx ON "SecurityLog" ("createdAt");
CREATE INDEX IF NOT EXISTS SiteVisit_path_idx ON "SiteVisit" ("path");
CREATE INDEX IF NOT EXISTS SiteVisit_createdAt_idx ON "SiteVisit" ("createdAt");
CREATE INDEX IF NOT EXISTS SiteVisit_sessionId_idx ON "SiteVisit" ("sessionId");
CREATE INDEX IF NOT EXISTS TeamMember_active_idx ON "TeamMember" ("active");
CREATE INDEX IF NOT EXISTS TeamMember_department_idx ON "TeamMember" ("department");
CREATE INDEX IF NOT EXISTS Job_active_idx ON "Job" ("active");
CREATE INDEX IF NOT EXISTS Job_department_idx ON "Job" ("department");
CREATE INDEX IF NOT EXISTS Keyword_status_idx ON "Keyword" ("status");
CREATE INDEX IF NOT EXISTS Keyword_type_idx ON "Keyword" ("type");
CREATE INDEX IF NOT EXISTS Ranking_keyword_idx ON "Ranking" ("keyword");
CREATE INDEX IF NOT EXISTS Ranking_date_idx ON "Ranking" ("date");
CREATE INDEX IF NOT EXISTS AiMention_platform_idx ON "AiMention" ("platform");
CREATE INDEX IF NOT EXISTS AiMention_date_idx ON "AiMention" ("date");
CREATE INDEX IF NOT EXISTS Backlink_status_idx ON "Backlink" ("status");
CREATE INDEX IF NOT EXISTS ContentBrief_status_idx ON "ContentBrief" ("status");
CREATE INDEX IF NOT EXISTS SeoIssue_status_idx ON "SeoIssue" ("status");
CREATE INDEX IF NOT EXISTS SeoIssue_severity_idx ON "SeoIssue" ("severity");
CREATE INDEX IF NOT EXISTS SeoReport_type_idx ON "SeoReport" ("type");
CREATE INDEX IF NOT EXISTS ClientLogo_active_idx ON "ClientLogo" ("active");
CREATE INDEX IF NOT EXISTS ClientLogo_category_idx ON "ClientLogo" ("category");

-- ============================================
-- 3. SEED DATA (idempotent — ON CONFLICT DO NOTHING)
-- ============================================
-- Admin user
INSERT INTO "User" (id, email, name, password, role, permissions, "createdAt", "updatedAt") VALUES ('admin-1', 'admin@clicktaketech.com', 'ClickTake Admin', 'ChangeMe!2025', 'admin', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (email) DO UPDATE SET password = EXCLUDED.password, role = EXCLUDED.role, permissions = EXCLUDED.permissions;

-- Pages (13 top-level + 24 service detail = 37)
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-home', 'home', 'Home', 'core', 'published', 'Engineering Tomorrow''s Intelligence, Today.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-services', 'services', 'Services', 'core', 'published', 'Full-spectrum engineering services.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-solutions', 'solutions', 'Solutions', 'core', 'published', 'Built for your business type.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-case-studies', 'case-studies', 'Case Studies', 'core', 'published', 'Real clients. Real numbers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-portfolio', 'portfolio', 'Portfolio', 'core', 'published', 'Production work, live right now.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-blog', 'blog', 'Blog', 'core', 'published', 'Field notes from the ClickTake team.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-pricing', 'pricing', 'Pricing', 'core', 'published', 'Transparent pricing.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-about', 'about', 'About', 'core', 'published', 'AI-native agency since 2019.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-team', 'team', 'Our Team', 'core', 'published', '28 people across 4 offices.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-careers', 'careers', 'Careers', 'core', 'published', 'Join ClickTake.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-cities', 'cities', 'Cities We Serve', 'core', 'published', 'Local presence, global delivery.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-connect', 'connect', 'Connect', 'core', 'published', 'Let''s connect.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, "createdAt", "updatedAt") VALUES ('page-contact', 'contact', 'Contact', 'core', 'published', 'Let''s build something extraordinary.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-ppc-paid-ads', 'ppc-paid-ads', 'PPC / Paid Ads', 'Digital Marketing', 'published', 'PPC / Paid Ads', 'We run profitable paid media across Google, Meta, LinkedIn and TikTok, built around a CPA target you set — not vanity clicks. Daily budget pacing, creative testing and landing-page CRO are baked in, with full-funnel GA4 and server-side tracking. You keep the ad accounts; we keep the spend working.', 'Google, Meta, LinkedIn & TikTok ad campaigns engineered around profitable CPA, not clicks. Full-funnel tracking from impression to revenue.', 'PPC Management Services | ClickTake', 'PPC management services across Google, Meta, LinkedIn and TikTok — engineered around profitable CPA. Book a free audit today.', 'PPC management services, Google Ads management, Meta Ads management, paid media agency, PPC advertising services, Google Ads agency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-content-strategy-seo', 'content-strategy-seo', 'Content Strategy & SEO', 'Digital Marketing', 'published', 'Content Strategy & SEO', 'We build topical authority, not blog posts — content clusters mapped to commercial intent and an editorial calendar your team can actually ship. Every brief targets a primary keyword with clear intent, internal links to your money pages, and a measurable SERP position to win.', 'Topical authority maps, content clusters, and editorial calendars that compound organic traffic month over month.', 'Content Strategy Services | ClickTake', 'Content strategy services that build topical authority: content clusters, editorial calendars and on-page SEO. Book a free content audit.', 'content strategy services, topical authority SEO, content clusters, editorial calendar services, SEO content marketing, content marketing agency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-conversion-rate-optimization', 'conversion-rate-optimization', 'Conversion Rate Optimization', 'Digital Marketing', 'published', 'Conversion Rate Optimization', 'We diagnose why visitors don''t convert and ship tests that move revenue — typically a 25-60% CVR lift within 90 days. Our playbook pairs session replay, funnel analysis and A/B testing on high-traffic pages, so every experiment is measurable. You get a prioritised roadmap, shipped tests and a learnings library.', 'A/B testing, heatmaps, and funnel analysis that lift checkout conversion by 25–60% without extra ad spend.', 'Conversion Rate Optimization Services', 'Conversion rate optimization services: A/B testing, heatmaps and funnel analysis that lift CVR 25-60%. Free CRO audit — book today.', 'conversion rate optimization services, CRO agency, A/B testing services, funnel analysis, heatmap analysis, landing page optimization', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-seo-services', 'seo-services', 'SEO Services', 'Digital Marketing', 'published', 'SEO Services', 'We run technical, on-page and off-page SEO as one system, not three disconnected workstreams. Crawlability, schema, internal links, content and backlinks compound toward defensible rankings. Local businesses get a top-3 Maps pack strategy; SaaS and ecommerce get programmatic SEO.', 'Technical, on-page, and off-page SEO. We move you into the top 3 of the local pack and keep you there.', 'SEO Services | Technical, On-Page & Local', 'SEO services covering technical, on-page and off-page SEO — built to land you in the top 3 local pack. Free SEO audit, book today.', 'SEO services, technical SEO audit, on-page SEO, off-page SEO services, local SEO services, SEO agency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-social-media-marketing', 'social-media-marketing', 'Social Media Marketing', 'Digital Marketing', 'published', 'Social Media Marketing', 'We run organic, paid, community and influencer as one engine, not four contractors. Organic builds reach, paid converts it, community turns customers into advocates, and influencer ops scale distribution. Every post has a commercial goal and every channel a defined funnel role.', 'Organic and paid social strategy that turns followers into a community and views into sales.', 'Social Media Marketing Services | ClickTake', 'Social media marketing services: organic content, paid social, community and influencer ops. Free strategy call — book today.', 'social media marketing services, social media management, paid social advertising, influencer marketing services, community management, social media agency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-seo-web-design-services', 'seo-web-design-services', 'SEO & Web Design Services', 'Digital Marketing', 'published', 'SEO & Web Design Services', 'We design websites that rank before they look pretty — PageSpeed 90+, full schema, clean crawl paths and zero render-blocking resources. Every page is indexable, every image optimised, every internal link mapped to commercial intent. You get a site that converts search visitors.', 'Sites built SEO-first from the ground up — fast, indexable, and structured for ranking from launch day.', 'SEO Web Design Services | ClickTake', 'SEO web design services: PageSpeed 90+, schema, indexability and SEO-first builds. Free technical design audit — book today.', 'SEO web design services, SEO-friendly websites, PageSpeed optimisation, schema markup, indexable web design, SEO-first web development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-full-stack-web-development', 'full-stack-web-development', 'Full-Stack Web Development', 'Web & Software', 'published', 'Full-Stack Web Development', 'We ship production web apps on Next.js 16, TypeScript, Prisma and Postgres, with Playwright E2E tests guarding every release. Type-safe APIs, server actions, optimistic UI, queued jobs and a real CI/CD pipeline. You get a codebase your team can own, not a black-box handover.', 'Next.js 16 + TypeScript + Prisma + Postgres. Design systems, Storybook, Playwright E2E, and CI/CD from day one.', 'Full-Stack Web Development Services', 'Full-stack web development with Next.js 16, TypeScript, Prisma, Postgres and Playwright E2E. Free architecture review — book today.', 'full-stack web development services, Next.js development agency, TypeScript web development, Prisma Postgres development, Playwright E2E testing, web application development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-saas-platform-engineering', 'saas-platform-engineering', 'SaaS Platform Engineering', 'Web & Software', 'published', 'SaaS Platform Engineering', 'We engineer SaaS platforms that scale from 10 to 10,000 tenants without rewrites — multi-tenant isolation, Stripe billing with usage metering, RBAC, and a daily-shipping release pipeline. Auth, billing, audit logs and observability are designed in from day one, not bolted on later.', 'Multi-tenant SaaS with billing (Stripe), RBAC, audit logs, and usage metering — architected to scale to 100K tenants.', 'SaaS Platform Engineering Services', 'SaaS platform engineering: multi-tenant architecture, Stripe billing, RBAC and usage metering. Free architecture review — book today.', 'SaaS platform engineering services, multi-tenant SaaS development, Stripe billing integration, RBAC implementation, usage metering, SaaS backend engineering', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-auth-identity', 'auth-identity', 'Auth & Identity', 'Web & Software', 'published', 'Auth & Identity', 'We build authentication that doesn''t get your users phished — NextAuth, OAuth/SAML SSO for enterprise, passkeys for passwordless, and zero-trust session management. MFA, device pairing, step-up auth and audit logs are designed in. You get a system your CISO can defend.', 'NextAuth, OAuth, SSO, SAML, and passkey-based authentication with zero-trust session handling.', 'Authentication & Identity Services', 'Authentication & identity services: NextAuth, OAuth/SAML SSO, passkeys and zero-trust sessions. Free security review — book today.', 'authentication & identity services, NextAuth development, OAuth SSO integration, SAML SSO services, passkey implementation, zero-trust session management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-python-backend-apis', 'python-backend-apis', 'Python Backend & APIs', 'Web & Software', 'published', 'Python Backend & APIs', 'We build Python backends that hold a p99 of 120ms under load — FastAPI for async requests, Celery or RQ workers for background jobs, REST or GraphQL with OpenAPI for clients, and proper connection pooling so the DB isn''t the bottleneck. Typed with Pydantic, tested with pytest, observable with OpenTelemetry.', 'FastAPI services, async workers, and typed REST/GraphQL APIs with OpenAPI docs and p99 120ms SLAs.', 'Python Backend & API Development', 'Python backend & API development with FastAPI, async workers, GraphQL and OpenAPI at p99 120ms. Free architecture review — book today.', 'Python backend & API development, FastAPI development, async Python workers, GraphQL API development, OpenAPI documentation, high-performance Python APIs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-wordpress-web-design-services', 'wordpress-web-design-services', 'WordPress Web Design Services', 'Web & Software', 'published', 'WordPress Web Design Services', 'We build WordPress sites that don''t slow you down — WooCommerce, ACF blocks, headless WP and Lighthouse 90+. Custom themes, custom blocks, an editing experience your team can use. No page-builder bloat and no plugins we''d be embarrassed to defend in a security review.', 'Custom WordPress + WooCommerce builds with headless options, ACF blocks, and Lighthouse 90+ performance.', 'WordPress Web Design Services | ClickTake', 'WordPress web design services: WooCommerce, ACF, headless WP and Lighthouse 90+. Free site audit — book today.', 'WordPress web design services, WooCommerce development, headless WordPress, ACF block development, WordPress SEO, Lighthouse optimisation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-ecommerce-web-design-services', 'ecommerce-web-design-services', 'Ecommerce Web Design Services', 'Web & Software', 'published', 'Ecommerce Web Design Services', 'We build ecommerce stores that load in 1.5s and convert 25-60% better — headless Shopify, Medusa or Next.js storefronts, Stripe checkout, CRO baked in. No theme bloat, no plugin soup, no checkout that loses carts. You get a store that''s fast, indexed and measurable.', 'Headless Shopify, Medusa, and custom commerce — sub-second LCP, +25–60% CVR, and infinite scale.', 'Ecommerce Web Design Services | ClickTake', 'Ecommerce web design services: headless Shopify/Medusa, Stripe, 1.5s LCP and +25-60% CVR. Free store audit — book today.', 'ecommerce web design services, headless Shopify development, Medusa commerce, Stripe ecommerce integration, Shopify Plus development, ecommerce CRO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-custom-llm-solutions', 'custom-llm-solutions', 'Custom LLM Solutions', 'AI & Automation', 'published', 'Custom LLM Solutions', 'We build LLM systems that ship to production — RAG over your real data, fine-tuning where it earns its keep, eval harnesses for regressions, guardrails for safe outputs, and cost controls. You get measured accuracy, a fallback chain and a runbook for misbehaviour.', 'Fine-tuned and RAG-grounded LLMs over your private data — with eval harnesses, guardrails, and cost controls.', 'Custom LLM Solutions | ClickTake', 'Custom LLM solutions: RAG, fine-tuning, eval harness, guardrails and cost control. Free architecture review — book today.', 'custom LLM solutions, RAG development, LLM fine-tuning services, LLM evaluation harness, AI guardrails, LLM cost optimisation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-ai-chatbots-assistants', 'ai-chatbots-assistants', 'AI Chatbots & Assistants', 'AI & Automation', 'published', 'AI Chatbots & Assistants', 'We build chatbots that actually do things — call your APIs, query your database, escalate to a human when stuck, and remember conversations across sessions. Deployed on your site, WhatsApp, Slack or Teams. You get a bot with a defined tool surface, human fallback and full conversation logs.', 'Production chatbots with tool-use, memory, and human handoff — deployed on your site, WhatsApp, and Slack.', 'AI Chatbot Development | ClickTake', 'AI chatbot development with tool-use, memory, human handoff and multi-channel deploy (site/WhatsApp/Slack). Free scope call — book today.', 'AI chatbot development, AI assistant development, tool-using LLM agents, conversational AI, human handoff chatbots, multi-channel AI assistants', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-prompt-engineering', 'prompt-engineering', 'Prompt Engineering', 'AI & Automation', 'published', 'Prompt Engineering', 'We engineer prompts like code — versioned, tested, evaluated against labelled sets, and optimised for cost and latency. No vibes, no ''we tried a few and this felt best''. You get a prompt library with version history, an eval suite that catches regressions, and per-prompt cost targets.', 'Systematic prompt design, evaluation, and version control for reliable LLM behaviour at scale.', 'Prompt Engineering Services | ClickTake', 'Prompt engineering services: versioning, eval suites, few-shot and cost optimisation. Free prompt audit — book today.', 'prompt engineering services, prompt versioning, LLM evaluation suites, few-shot prompting, prompt optimisation, LLM cost reduction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-computer-vision-nlp', 'computer-vision-nlp', 'Computer Vision & NLP', 'AI & Automation', 'published', 'Computer Vision & NLP', 'We build computer vision and NLP systems that work in production — OCR, object detection, document AI and text classification, trained on your data and deployable on cloud or edge. No ''we trained a model'' demos — you get measured accuracy, an eval harness and a deploy plan.', 'OCR, object detection, document intelligence, and classification models deployed to production endpoints.', 'Computer Vision & NLP Services', 'Computer vision & NLP: OCR, object detection, document AI, classification and edge deployment. Free scope call — book today.', 'computer vision & NLP services, OCR development, object detection models, document AI, text classification, edge AI deployment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-ai-automation', 'ai-automation', 'AI Automation', 'AI & Automation', 'published', 'AI Automation', 'We automate the workflows eating your team''s week — invoicing, onboarding, lead routing, reports and support triage — with AI where it earns its keep and deterministic code elsewhere. Human-in-the-loop, monitoring on every job, kill switch included. Typically 30+ hrs/wk saved in 90 days.', 'Workflows that eliminate 30+ hours/week of manual work — connecting your tools with intelligent agents.', 'AI Automation Services | ClickTake', 'AI automation services that eliminate 30+ hrs/wk of manual work — workflow orchestration, integrations and monitoring. Free scope call — book today.', 'AI automation services, workflow automation, AI agent orchestration, human-in-the-loop automation, integration automation, business process automation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-ai-agent-development', 'ai-agent-development', 'AI Agent Development', 'AI & Automation', 'published', 'AI Agent Development', 'We build production AI agents that plan, use tools, remember context and orchestrate with others — not single-shot LLM calls. LangGraph for stateful orchestration, structured memory, tool-use with retries, and eval suites. You get an agent that completes multi-step tasks reliably.', 'Autonomous goal-pursuing agents with planning, memory, and multi-agent orchestration via LangGraph.', 'AI Agent Development Services | ClickTake', 'AI agent development: LangGraph, planning, memory, multi-agent orchestration and production evals. Free scope call — book today.', 'AI agent development services, LangGraph development, multi-agent orchestration, agent memory systems, AI planning agents, agent evaluation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-graphic-design', 'graphic-design', 'Graphic Design', 'Creative & Brand', 'published', 'Graphic Design', 'We design brand identities that hold up across every touchpoint — logos, type, colour, marketing collateral, social creatives and enforceable guidelines. Not a logo on a slide; a system that scales from billboard to favicon. You get formats your team can actually use.', 'Logos, brand systems, marketing collateral, and social creatives that look premium and convert.', 'Graphic Design Services | ClickTake', 'Graphic design services: brand identity, logos, marketing collateral and social creatives. Free brand audit — book today.', 'graphic design services, brand identity design, logo design services, marketing collateral design, social media creatives, brand guidelines', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-professional-web-design-services', 'professional-web-design-services', 'Professional Web Design Services', 'Creative & Brand', 'published', 'Professional Web Design Services', 'We design websites the way senior product teams do — UX research, user flows, wireframes, Figma design systems and hi-fi prototypes user-tested before code. No design by committee. You get a design system your developers can implement and marketers can extend.', 'Conversion-focused web design with UX research, wireframes, and pixel-perfect Figma handoff.', 'Professional Web Design Services | ClickTake', 'Professional web design services: UX research, wireframes, Figma design systems and hi-fi prototypes. Free UX audit — book today.', 'professional web design services, UX research services, wireframe design, Figma design systems, high-fidelity prototypes, user experience design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-b2b-video-production', 'b2b-video-production', 'B2B Video Production', 'Creative & Brand', 'published', 'B2B Video Production', 'We produce B2B videos that earn their place in your funnel — explainers that shorten sales cycles, demos that drive trials, ad creatives that lower CPA, motion graphics that simplify. Scripted, shot and edited in every aspect ratio each platform needs. Every video has a job.', 'Explainer videos, product demos, and ad creatives — scripted, shot, and edited end-to-end.', 'B2B Video Production Services | ClickTake', 'B2B video production: explainer videos, product demos, ad creatives and motion graphics. Free creative scoping — book today.', 'B2B video production services, explainer video production, product demo videos, ad creative video, motion graphics, corporate video production', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-web-design-services', 'web-design-services', 'Web Design Services', 'Creative & Brand', 'published', 'Web Design Services', 'We design websites end-to-end — research, IA, wireframes, design systems, UI kits, dev handoff and design QA through to launch. One team owns the design from first sketch to shipped site, so what you saw in Figma is what goes live. No ''the developer didn''t quite get it right''.', 'End-to-end web design from concept to launch — design systems, UI kits, and developer handoff.', 'Web Design Services | ClickTake', 'Web design services: end-to-end design systems, UI kits, dev handoff and design QA. Free design audit — book today.', 'web design services, design systems, UI kits, design handoff, design QA, responsive web design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-small-business-web-design-services', 'small-business-web-design-services', 'Small Business Web Design Services', 'Creative & Brand', 'published', 'Small Business Web Design Services', 'We build small business websites that launch in weeks, rank locally and your team can update without calling us — mobile-first, local-SEO ready, on a CMS your staff can run. No bloated retainers, no locked editing, no per-page invoices. You get a site that earns its keep from day one.', 'Affordable, fast-launch websites for small businesses — local-SEO-ready and conversion-optimized.', 'Small Business Web Design Services', 'Small business web design services: fast launch, local-SEO ready, mobile-first and easy CMS. Free scope call — book today.', 'small business web design services, small business website design, local SEO ready websites, easy CMS websites, fast launch websites, mobile-first small business sites', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Page" (id, slug, title, category, status, hero, overview, body, "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") VALUES ('page-responsive-web-design-services', 'responsive-web-design-services', 'Responsive Web Design Services', 'Creative & Brand', 'published', 'Responsive Web Design Services', 'We design responsive websites that work on every device — mobile-first layouts, fluid type, zero CLS and WCAG 2.2 AA accessibility built in. Engineered against Core Web Vitals, tested with screen readers. You get a site that ranks, converts and is usable by every customer.', 'Flawless experiences across every device — mobile, tablet, desktop, and ultra-wide — with no layout shifts.', 'Responsive Web Design Services | ClickTake', 'Responsive web design services: mobile-first, fluid layouts, no CLS and WCAG 2.2 AA. Free accessibility audit — book today.', 'responsive web design services, mobile-first web design, fluid layout design, CLS-free websites, WCAG 2.2 AA accessibility, responsive web development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;

-- Blog posts
INSERT INTO "BlogPost" (id, slug, title, category, excerpt, body, status, "readTime", "createdAt", "updatedAt", "publishedAt") VALUES ('blog-blog-7-best-ai-chatbots-for-capturing-website-leads-2026', 'blog-7-best-ai-chatbots-for-capturing-website-leads-2026', '7 Best AI Chatbots for Capturing Website Leads (2026)', 'AI Automation', 'If you''re asking what is the best AI chatbot for capturing leads on a website, the answer depends on something most buying guides skip entirely: whether the bot actually qualifies prospects or merely collects their contact details.', 'If you''re asking what is the best AI chatbot for capturing leads on a website, the answer depends on something most buying guides skip entirely: whether the bot actually qualifies prospects or merely collects their contact details.', 'published', '14 min', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "BlogPost" (id, slug, title, category, excerpt, body, status, "readTime", "createdAt", "updatedAt", "publishedAt") VALUES ('blog-blog-7-social-media-content-types-that-actually-drive-sales', 'blog-7-social-media-content-types-that-actually-drive-sales', '7 social media content types that actually drive sales', 'Digital Marketing', 'Most brands measure social media performance by likes, shares, and follower growth. These metrics feel meaningful; they''re easy to report, and they generate the kind of positive momentum that keeps stakeholders happy in a monthly review.', 'Most brands measure social media performance by likes, shares, and follower growth. These metrics feel meaningful; they''re easy to report, and they generate the kind of positive momentum that keeps stakeholders happy in a monthly review.', 'published', '11 min', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "BlogPost" (id, slug, title, category, excerpt, body, status, "readTime", "createdAt", "updatedAt", "publishedAt") VALUES ('blog-blog-ai-automations-that-actually-work-for-small-businesses', 'blog-ai-automations-that-actually-work-for-small-businesses', 'AI Automations That Actually Work for Small Businesses', 'AI Automation', 'If you''re wondering what AI automations actually work for small businesses, you''re not alone — and the answer is more straightforward than most vendors make it sound.', 'If you''re wondering what AI automations actually work for small businesses, you''re not alone — and the answer is more straightforward than most vendors make it sound.', 'published', '12 min', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "BlogPost" (id, slug, title, category, excerpt, body, status, "readTime", "createdAt", "updatedAt", "publishedAt") VALUES ('blog-blog-ai-business-automation-what-actually-works-for-smes', 'blog-ai-business-automation-what-actually-works-for-smes', 'AI business automation: what actually works for SMEs', 'AI Automation', 'A practical breakdown of the AI automations that deliver real ROI for small and medium enterprises — and the ones that are smoke and mirrors.', 'A practical breakdown of the AI automations that deliver real ROI for small and medium enterprises — and the ones that are smoke and mirrors.', 'published', '13 min', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "BlogPost" (id, slug, title, category, excerpt, body, status, "readTime", "createdAt", "updatedAt", "publishedAt") VALUES ('blog-blog-how-to-build-a-social-media-content-strategy-in-2026', 'blog-how-to-build-a-social-media-content-strategy-in-2026', 'How to build a social media content strategy in 2026', 'Digital Marketing', 'A repeatable framework for building a social media content strategy that compounds — from audience research to editorial calendar to measurement.', 'A repeatable framework for building a social media content strategy that compounds — from audience research to editorial calendar to measurement.', 'published', '15 min', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "BlogPost" (id, slug, title, category, excerpt, body, status, "readTime", "createdAt", "updatedAt", "publishedAt") VALUES ('blog-blog-leading-platforms-for-website-user-behavior-analytics-in-2026', 'blog-leading-platforms-for-website-user-behavior-analytics-in-2026', 'Leading Platforms for Website User Behavior Analytics in 2026', 'Web', 'A technical comparison of the leading user behavior analytics platforms — PostHog, FullStory, Hotjar, Microsoft Clarity — and when to pick each.', 'A technical comparison of the leading user behavior analytics platforms — PostHog, FullStory, Hotjar, Microsoft Clarity — and when to pick each.', 'published', '16 min', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "BlogPost" (id, slug, title, category, excerpt, body, status, "readTime", "createdAt", "updatedAt", "publishedAt") VALUES ('blog-blog-next-js-pagespeed-optimisation-how-to-hit-90-scores', 'blog-next-js-pagespeed-optimisation-how-to-hit-90-scores', 'Next.js PageSpeed optimisation: how to hit 90+ scores', 'Web', 'The exact performance patterns we use to ship Next.js 16 apps that hit 90+ Lighthouse scores — from RSC to image optimization to edge caching.', 'The exact performance patterns we use to ship Next.js 16 apps that hit 90+ Lighthouse scores — from RSC to image optimization to edge caching.', 'published', '13 min', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "BlogPost" (id, slug, title, category, excerpt, body, status, "readTime", "createdAt", "updatedAt", "publishedAt") VALUES ('blog-blog-seo-audit-checklist-25-steps-to-rank-higher-in-2026', 'blog-seo-audit-checklist-25-steps-to-rank-higher-in-2026', 'SEO Audit Checklist: 25 Steps to Rank Higher in 2026', 'SEO', 'The exact 25-step technical SEO audit we run on every new engagement — covering crawlability, indexation, Core Web Vitals, structured data, and content gaps.', 'The exact 25-step technical SEO audit we run on every new engagement — covering crawlability, indexation, Core Web Vitals, structured data, and content gaps.', 'published', '20 min', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "BlogPost" (id, slug, title, category, excerpt, body, status, "readTime", "createdAt", "updatedAt", "publishedAt") VALUES ('blog-blog-social-media-for-ecommerce-turning-views-into-sales', 'blog-social-media-for-ecommerce-turning-views-into-sales', 'Social media for ecommerce: turning views into sales', 'Ecommerce', 'How D2C brands turn social media views into actual sales — the content formats, funnel design, and attribution models that work in 2026.', 'How D2C brands turn social media views into actual sales — the content formats, funnel design, and attribution models that work in 2026.', 'published', '12 min', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;

-- Pricing tiers
INSERT INTO "PricingTier" (id, name, tagline, audience, price, cadence, popular, features, "notIncluded", cta, status, "createdAt", "updatedAt") VALUES ('tier-starter', 'Starter', 'For new founders & local businesses', 'From £1,500', '£1,500', 'one-off project', FALSE, 'Up to 5-page mobile-first Next.js website\nGoogle Business Profile setup + optimization\nFoundational on-page SEO (titles, meta, schema, sitemap)\nContact form with spam protection + email notifications\nSSL, CDN, analytics and Search Console setup\nDomain + 1 year managed hosting\n2 rounds of revisions\n14-day post-launch support', 'AI chatbot or automation\nOngoing monthly SEO\nPaid media management', 'Start with Starter', 'published', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (name) DO NOTHING;
INSERT INTO "PricingTier" (id, name, tagline, audience, price, cadence, popular, features, "notIncluded", cta, status, "createdAt", "updatedAt") VALUES ('tier-growth', 'Growth', 'For scaling brands & e-commerce stores', 'From £6,000', '£6,000', 'one-off + monthly retainer', TRUE, 'Production-ready website or e-commerce rebuild\nHeadless commerce (Shopify / Medusa) with 1.5s LCP\nAI automation (chatbot, lead scoring, or workflow)\nOngoing monthly SEO (technical + content)\nPaid media management (Google + Meta)\nConversion rate optimization (A/B testing)\nDesign system in Storybook + Playwright E2E\nWeekly demos + 30-day post-launch hypercare', 'Multi-agent orchestration\nCustom LLM fine-tuning', 'Start with Growth', 'published', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (name) DO NOTHING;
INSERT INTO "PricingTier" (id, name, tagline, audience, price, cadence, popular, features, "notIncluded", cta, status, "createdAt", "updatedAt") VALUES ('tier-scale', 'Scale', 'For SaaS platforms & enterprises', 'From £18,000', '£18,000', 'one-off + monthly retainer', FALSE, 'Multi-tenant SaaS platform engineering\nCustom AI / multi-agent orchestration (LangGraph)\nCloud DevOps (AWS/GCP/Azure) with Terraform IaC\nKubernetes autoscaling + observability stack\nSOC 2 Type II audit prep + security hardening\nDedicated lead engineer + 4-person pod\np99 120ms SLA + 99.9% uptime guarantee\n24/7 on-call runbook + quarterly roadmapping', '', 'Start with Scale', 'published', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (name) DO NOTHING;
INSERT INTO "PricingTier" (id, name, tagline, audience, price, cadence, popular, features, "notIncluded", cta, status, "createdAt", "updatedAt") VALUES ('tier-custom-quote', 'Custom Quote', 'For something that doesn''t fit a box', 'Let''s scope it', 'Custom', 'scoped in a free 30-min call', FALSE, 'Fixed-scope, fixed-fee PoC in 6 weeks\nSenior engineer (not salesperson) on the call\nDraft architecture + ballpark estimate\nPick any mix of the 24 services\nNo long-term contract required to start\nNDA signed before any discovery call\nUK Ltd Co + GDPR-compliant invoicing\nCode + keys handed over, never locked in', '', 'Book a discovery call', 'published', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (name) DO NOTHING;

-- Team members (6)
INSERT INTO "TeamMember" (id, name, role, department, bio, "order", active, "createdAt", "updatedAt") VALUES ('sarah-mitchell', 'Sarah Mitchell', 'Founder & CEO', 'Leadership', 'Founded ClickTake in 2019. 15+ years in software engineering and AI.', 1, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "TeamMember" (id, name, role, department, bio, "order", active, "createdAt", "updatedAt") VALUES ('james-o-connor', 'James O''Connor', 'CTO', 'Leadership', 'Leads the engineering practice. Ex-AWS, ex-fintech.', 2, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "TeamMember" (id, name, role, department, bio, "order", active, "createdAt", "updatedAt") VALUES ('aisha-khan', 'Aisha Khan', 'Head of Growth', 'Marketing', 'Drives SEO, paid, and content strategy across all clients.', 3, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "TeamMember" (id, name, role, department, bio, "order", active, "createdAt", "updatedAt") VALUES ('aisha-al-mansoori', 'Aisha Al-Mansoori', 'MENA Director', 'Operations', 'Heads the Dubai office and MENA client relationships.', 4, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "TeamMember" (id, name, role, department, bio, "order", active, "createdAt", "updatedAt") VALUES ('david-chen', 'David Chen', 'Lead AI Engineer', 'Development', 'Ships multi-agent systems and RAG pipelines to production.', 5, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "TeamMember" (id, name, role, department, bio, "order", active, "createdAt", "updatedAt") VALUES ('maria-santos', 'Maria Santos', 'Creative Director', 'Creative', 'Leads brand identity and web design across all engagements.', 6, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;

-- Jobs
INSERT INTO "Job" (id, slug, title, department, location, type, description, active, "createdAt", "updatedAt") VALUES ('job-senior-nextjs-engineer', 'senior-nextjs-engineer', 'Senior Next.js Engineer', 'Web & Software', 'Remote · UK / Pakistan', 'Full-time', 'Lead production Next.js 16 builds for enterprise clients. Own architecture, CI/CD, and mentor mid-level engineers.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Job" (id, slug, title, department, location, type, description, active, "createdAt", "updatedAt") VALUES ('job-ai-ml-engineer', 'ai-ml-engineer', 'AI / ML Engineer', 'AI & Automation', 'Remote · UK / Pakistan', 'Full-time', 'Design and ship multi-agent systems, RAG pipelines, and custom LLM solutions with evals and guardrails.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Job" (id, slug, title, department, location, type, description, active, "createdAt", "updatedAt") VALUES ('job-seo-specialist', 'seo-specialist', 'SEO Specialist', 'Digital Marketing', 'Birmingham, UK · Hybrid', 'Full-time', 'Drive technical, on-page, and local SEO for clients across 4 continents. Own rankings, Core Web Vitals, and reporting.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Job" (id, slug, title, department, location, type, description, active, "createdAt", "updatedAt") VALUES ('job-graphic-designer', 'graphic-designer', 'Graphic Designer', 'Creative & Brand', 'Dubai, UAE · Hybrid', 'Full-time', 'Craft brand identities, marketing creatives, and web design systems for clients across the UK, US and MENA.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Job" (id, slug, title, department, location, type, description, active, "createdAt", "updatedAt") VALUES ('job-frontend-engineer-intern', 'frontend-engineer-intern', 'Frontend Engineer Intern', 'Web & Software', 'Multan, Pakistan · On-site', 'Internship', 'Learn production Next.js, React, and TypeScript alongside senior engineers. Paid, 3-month rotational program.', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;

-- Client logos (8)
INSERT INTO "ClientLogo" (id, name, logo, website, category, "order", active, "createdAt") VALUES ('dibnow', 'DibNow', '', 'https://dibnow.com', 'saas', 1, TRUE, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "ClientLogo" (id, name, logo, website, category, "order", active, "createdAt") VALUES ('panel-employee-management', 'Panel — Employee Management', '', '', 'saas', 2, TRUE, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "ClientLogo" (id, name, logo, website, category, "order", active, "createdAt") VALUES ('logitrack', 'LogiTrack', '', '', 'saas', 3, TRUE, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "ClientLogo" (id, name, logo, website, category, "order", active, "createdAt") VALUES ('clickopticx', 'ClickOpticX', '', '', 'saas', 4, TRUE, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "ClientLogo" (id, name, logo, website, category, "order", active, "createdAt") VALUES ('mearns-gadget-repair', 'Mearns Gadget Repair', '', '', 'repair', 5, TRUE, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "ClientLogo" (id, name, logo, website, category, "order", active, "createdAt") VALUES ('gadget-doctor-ls', 'Gadget Doctor LS', '', '', 'repair', 6, TRUE, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "ClientLogo" (id, name, logo, website, category, "order", active, "createdAt") VALUES ('academy-portal', 'Academy Portal', '', '', 'education', 7, TRUE, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;
INSERT INTO "ClientLogo" (id, name, logo, website, category, "order", active, "createdAt") VALUES ('learnhub', 'LearnHub', '', '', 'education', 8, TRUE, CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING;

-- Site settings
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-site-name', 'site_name', 'ClickTake Technologies', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-tagline', 'tagline', 'Engineering Tomorrow''s Intelligence, Today.', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-logo-url', 'logo_url', '/logo-dark.png', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-logo-white-url', 'logo_white_url', '/logo-white.png', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-favicon-url', 'favicon_url', '/logo.svg', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-brand-color-primary', 'brand_color_primary', '#136DFF', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-brand-color-secondary', 'brand_color_secondary', '#FF53A9', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-dashboard-bg-color', 'dashboard_bg_color', '#0a0e1a', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-dashboard-card-color', 'dashboard_card_color', '#141828', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-dashboard-accent-color', 'dashboard_accent_color', '#136DFF', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-timezone', 'timezone', 'Asia/Karachi', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-contact-email', 'contact_email', 'info@clicktaketech.com', 'contact', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-contact-phone-uk', 'contact_phone_uk', '+44 7391 653377', 'contact', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-contact-phone-pk', 'contact_phone_pk', '+92 306 9753003', 'contact', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-whatsapp', 'whatsapp', '+44 7391 653377', 'contact', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-address-hq', 'address_hq', 'Flat 312 Kitts Green Road, Birmingham, B33 9SB, UK', 'contact', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-address-lat', 'address_lat', '52.4680', 'contact', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-address-lng', 'address_lng', '-1.7860', 'contact', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-hours-monday', 'hours_monday', '9:00 AM - 6:00 PM', 'hours', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-hours-tuesday', 'hours_tuesday', '9:00 AM - 6:00 PM', 'hours', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-hours-wednesday', 'hours_wednesday', '9:00 AM - 6:00 PM', 'hours', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-hours-thursday', 'hours_thursday', '9:00 AM - 6:00 PM', 'hours', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-hours-friday', 'hours_friday', '9:00 AM - 6:00 PM', 'hours', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-hours-saturday', 'hours_saturday', '10:00 AM - 4:00 PM', 'hours', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-hours-sunday', 'hours_sunday', 'Closed', 'hours', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-target-areas', 'target_areas', 'Birmingham, London, Manchester, Leeds, Austin TX, New York, San Francisco, Dubai, Abu Dhabi, Multan, Lahore, Karachi, Islamabad', 'target', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-service-radius-km', 'service_radius_km', '50', 'target', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-default-meta-title', 'default_meta_title', 'ClickTake Technologies — AI-Native Software Engineering & Digital Agency', 'seo', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-default-meta-description', 'default_meta_description', 'ClickTake ships production-grade software, AI agents, cloud architecture, digital marketing & creative services across 4 continents.', 'seo', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-google-analytics-id', 'google_analytics_id', '', 'seo', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-google-site-verification', 'google_site_verification', '', 'seo', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-facebook-url', 'facebook_url', 'https://www.facebook.com/clicktaketechnologies/', 'social', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-instagram-url', 'instagram_url', 'https://www.instagram.com/clicktaketechologiesuk/', 'social', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-linkedin-url', 'linkedin_url', 'https://www.linkedin.com/company/click-take-technologies/', 'social', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-youtube-url', 'youtube_url', 'https://www.youtube.com/channel/UCt527M4hxeFOavWdXSRTsdw', 'social', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-tumblr-url', 'tumblr_url', 'https://www.tumblr.com/clicktaketechnologies', 'social', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-tiktok-url', 'tiktok_url', 'https://www.tiktok.com/@clicktaketechnologiesuk', 'social', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-pinterest-url', 'pinterest_url', 'https://uk.pinterest.com/clicktaketechnologies/', 'social', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-threads-url', 'threads_url', 'https://www.threads.com/@clicktaketech', 'social', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-stripe-publishable-key', 'stripe_publishable_key', '', 'integrations', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-recaptcha-site-key', 'recaptcha_site_key', '', 'integrations', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "SiteSetting" (id, key, value, category, "updatedAt") VALUES ('setting-maintenance-mode', 'maintenance_mode', 'off', 'identity', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;

-- Theme variables (9)
INSERT INTO "ThemeVariable" (id, key, value, category, "updatedAt") VALUES ('theme---color-primary', '--color-primary', '#136DFF', 'color', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "ThemeVariable" (id, key, value, category, "updatedAt") VALUES ('theme---color-accent', '--color-accent', '#FF53A9', 'color', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "ThemeVariable" (id, key, value, category, "updatedAt") VALUES ('theme---color-background', '--color-background', '#0a0e1a', 'color', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "ThemeVariable" (id, key, value, category, "updatedAt") VALUES ('theme---color-foreground', '--color-foreground', '#f8fafc', 'color', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "ThemeVariable" (id, key, value, category, "updatedAt") VALUES ('theme---color-card', '--color-card', '#141828', 'color', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "ThemeVariable" (id, key, value, category, "updatedAt") VALUES ('theme---color-border', '--color-border', 'rgba(255,255,255,0.1)', 'color', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "ThemeVariable" (id, key, value, category, "updatedAt") VALUES ('theme---radius', '--radius', '0.75rem', 'radius', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "ThemeVariable" (id, key, value, category, "updatedAt") VALUES ('theme---font-sans', '--font-sans', 'Geist, system-ui, sans-serif', 'font', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;
INSERT INTO "ThemeVariable" (id, key, value, category, "updatedAt") VALUES ('theme---font-mono', '--font-mono', 'Geist Mono, monospace', 'font', CURRENT_TIMESTAMP) ON CONFLICT (key) DO NOTHING;

-- Typography preset
INSERT INTO "TypographyPreset" (id, name, "fontFamily", "headingScale", "bodySize", "lineHeight", active, "createdAt") VALUES ('typography-default', 'Default', 'Geist, system-ui, sans-serif', '1.25', '16px', '1.6', TRUE, CURRENT_TIMESTAMP) ON CONFLICT (name) DO NOTHING;

-- ============================================
-- DONE! All 28 tables created + data seeded.
-- Your admin panel at clicktaketech.com/#admin
-- will now show all data.
-- ============================================