import { NextRequest, NextResponse } from "next/server";

/**
 * Middleware for AI agent discovery (RFC 8288, RFC 9727).
 *
 * 1. Link headers on homepage — points agents to machine-readable
 *    discovery resources (api-catalog, service-desc, service-doc,
 *    describedby, oauth-protected-resource).
 *
 * 2. Markdown content negotiation — requests with
 *    `Accept: text/markdown` (or including it) get a Link header pointing
 *    to the markdown representation. The actual markdown is generated by
 *    the page-level logic; this middleware just adds the discovery header.
 *
 * Per RFC 9727 Section 3, the `Link` header is the primary discovery
 * mechanism for agents — they don't need to guess `/.well-known/` paths.
 */

export function middleware(req: NextRequest) {
  const res = NextResponse.next();
  const path = req.nextUrl.pathname;

  // Only add Link headers on the homepage (and only for GET).
  if (req.method === "GET" && (path === "/" || path === "")) {
    const accept = req.headers.get("accept") || "";

    // Build the Link header value — comma-separated for efficiency.
    const links = [
      `</.well-known/api-catalog>; rel="api-catalog"`,
      `</.well-known/oauth-protected-resource>; rel="describedby"`,
      `</api/openapi.json>; rel="service-desc"; type="application/json"`,
      `</api/docs>; rel="service-doc"; type="text/html"`,
      `</.well-known/agent-card.json>; rel="describedby"; type="application/json"`,
      `</.well-known/oauth-authorization-server>; rel="service-doc"`,
      `</.well-known/mcp/server-card.json>; rel="describedby"; type="application/json"`,
      `</.well-known/agent-skills/index.json>; rel="describedby"; type="application/json"`,
    ];
    res.headers.set("Link", links.join(", "));

    // Content-Signal in the response too (belt + suspenders with robots.txt)
    res.headers.set("Content-Signal", "ai-train=no, search=yes, ai-input=no");

    // Markdown negotiation hint — tell agents that a markdown
    // representation is available via Accept: text/markdown
    if (accept.includes("text/markdown") || accept.includes("text/x-markdown")) {
      // The page.tsx client component checks Accept and renders markdown,
      // but since this is a SPA, the middleware adds a Vary header so
      // caches know the response varies by Accept.
      res.headers.set("Vary", "Accept");
      // Add a hint header that markdown is preferred
      res.headers.set(
        "X-Content-Type-Options",
        "text/markdown available via Accept: text/markdown"
      );
    }
  }

  return res;
}

export const config = {
  // Only run on the homepage — keep middleware fast for all other routes.
  matcher: ["/"],
};
